### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by JIzabal** [mYang25/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - Commands, java files, and other code should be written with backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Fix the last step so that the command runs the code on the remote server: Optimizing Remote Running (this is from the lab in week 1) - Write down in notes First try using just what we learned in this lab, and document the best process you came up with. Try to get the total time for a run after editing and saving to under 10 total keystrokes/mouse clicks, including all typing.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by JIzabal** [comment]
We wanted you to make a local edit to WhereAmI.java, copy it to the remote server, and run it as described in the comment above. I'm unsure if this is done in the images, because the images don't show up. Otherwise, see the explanation below to see how to fix this:

We want you to copy the code from your computer to the remote server, compile the code that was copied onto the remote server, and then run the code that was compiled on the remote server. First, look into Part 5 of Lab 1 to see how to copy a file locally to the remote server using `scp`. Then, look into Part 7 of Lab 1 to see how to run commands (e.g., `javac` and `java`) on the remote server. There's an example of how to do this with `ls` but you need to do it for `javac` and `java`. Finally, see Part 7 of Lab 1 to figure out how to combine this all into one line through the use of semicolons. Let me know if you have any questions! Once you're done, go ahead and submit a regrade request.

**Comment by mYang25** [comment]
I forgot to update the picture path (I moved them all into a folder). The images should show up now. Also in the last picture, I did all of the above. Please check for a lab resubmission. Thank you very much :>

**Comment by JIzabal** [comment]
Currently your picture shows that you're copying, compiling, and running all in one line on the remote server. This is a great start, however we want you to copy (using `scp`) your Java file from your local computer to the remote server. Then, as seen in Part 7 of the lab, compile and run your code while running a command locally. Please read my comment from earlier to see how to do this.

**Comment by JIzabal** [comment]
You're almost there! Keep in mind that after `scp`, there's no need to use `cp`. Also, you only need to be working with `WhereAmI.java`, so you can get rid of `OtherMain.java`.

**Comment by JIzabal** [comment]
The `javac` and `java` commands need to be run on the server, similar to how it's done [here](https://ucsd-cse15l-w22.github.io/week/week1/#part-7-making-remote-running-even-more-pleasant) with the `ls` command.

**Comment by mYang25** [comment]
Fixed and updated.

**Comment by JIzabal** [comment]
Good job!
